/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        error: "#ba1a1a",
        "surface-bright": "#f8f9ff",
        "on-tertiary-fixed-variant": "#444749",
        "on-tertiary-container": "#818486",
        "inverse-on-surface": "#eaf1ff",
        "inverse-primary": "#bec6e0",
        "on-error-container": "#93000a",
        outline: "#76777d",
        "on-primary": "#ffffff",
        "surface-container-high": "#dce9ff",
        "surface-variant": "#d3e4fe",
        "on-secondary-fixed": "#001f26",
        "inverse-surface": "#213145",
        "surface-container-lowest": "#ffffff",
        background: "#f8f9ff",
        "surface-tint": "#565e74",
        "on-tertiary-fixed": "#191c1e",
        "tertiary-container": "#191c1e",
        "outline-variant": "#c6c6cd",
        "on-surface": "#0b1c30",
        "on-secondary-fixed-variant": "#004e5c",
        "surface-container-highest": "#d3e4fe",
        primary: "#000000",
        "on-secondary-container": "#006172",
        "surface-container-low": "#eff4ff",
        "secondary-fixed": "#acedff",
        "primary-fixed-dim": "#bec6e0",
        "on-background": "#0b1c30",
        "tertiary-fixed": "#e0e3e5",
        "error-container": "#ffdad6",
        "on-primary-container": "#7c839b",
        "primary-fixed": "#dae2fd",
        secondary: "#00687a",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#4cd7f6",
        "on-primary-fixed-variant": "#3f465c",
        "secondary-container": "#57dffe",
        "primary-container": "#131b2e",
        surface: "#f8f9ff",
        "on-surface-variant": "#45464d",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-container": "#e5eeff",
        "on-primary-fixed": "#131b2e",
        "surface-dim": "#cbdbf5",
        tertiary: "#000000",
        "tertiary-fixed-dim": "#c4c7c9",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-padding-mobile": "1.25rem",
        "stack-sm": "0.5rem",
        unit: "8px",
        gutter: "1rem",
        "container-padding-desktop": "2.5rem",
        "stack-lg": "2rem",
        "stack-md": "1rem",
      },
      fontFamily: {
        h3: ["Sora"],
        "label-caps": ["Inter"],
        "body-md": ["Inter"],
        h1: ["Sora"],
        h2: ["Sora"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        h3: [
          "24px",
          {
            lineHeight: "1.3",
            fontWeight: "500",
          },
        ],
        "label-caps": [
          "12px",
          {
            lineHeight: "1",
            letterSpacing: "0.05em",
            fontWeight: "600",
          },
        ],
        "body-md": [
          "16px",
          {
            lineHeight: "1.5",
            fontWeight: "400",
          },
        ],
        h1: [
          "40px",
          {
            lineHeight: "1.2",
            letterSpacing: "-0.02em",
            fontWeight: "600",
          },
        ],
        h2: [
          "32px",
          {
            lineHeight: "1.25",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "body-sm": [
          "14px",
          {
            lineHeight: "1.5",
            fontWeight: "400",
          },
        ],
        "body-lg": [
          "18px",
          {
            lineHeight: "1.6",
            fontWeight: "400",
          },
        ],
      },
    },
  },
  plugins: [],
};
